public class Task02 {
    public static void main(String[] args) {
        System.out.println("Да, можно использовать try с finally.");
        // Да.
        // Конструкция try с finally допустима тк finally гарантирует выполнение кода в нём
        // независимо от того, было ли выброшено исключение.
    }
}